import Link from 'next/link';
import {PageShell,Photo,ReservationLink,Arrow} from '../src/components/Editorial';
import HomeMotion from '../src/components/HomeMotion';
import PopupCookies from '../src/components/PopupCookies';
import {suites,meals,experiences,promotions} from '../src/data/content';
import {homeMedia} from '../src/data/home';
import {site} from '../src/data/site';
import styles from './Home.module.css';
export const metadata={alternates:{canonical:'/'}};
const business={'@context':'https://schema.org','@type':'LodgingBusiness',name:'Private Motel',url:site.url,telephone:site.phone,image:site.url+'/images/motel-entrada.jpg',address:{'@type':'PostalAddress',streetAddress:'Rua Adelino Bianchini, 86',addressLocality:'Cambé',addressRegion:'PR',addressCountry:'BR'},sameAs:[site.instagram,site.facebook]};
const PhotoLink=({href,media,className='',sizes})=><Link href={href} className={className}><Photo {...media} sizes={sizes}/></Link>;
export default function Home(){return <PageShell><HomeMotion><div className={styles.home}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(business).replace(/</g,'\\u003c')}}/>
<section className={styles.hero}><Photo {...homeMedia.hero} priority sizes="100vw" className={styles.heroMedia}/><div className={styles.heroShade}/><div className={styles.heroContent}><h1>Entre.<br/><em>O tempo é seu.</em></h1><p>Um encontro. Um refúgio.<br/>O mundo lá fora pode esperar.</p><div className={styles.heroActions}><ReservationLink/><Link className="button-secondary" href="/suites">Conheça as suítes <Arrow/></Link></div></div><div className={styles.heroFoot}><span>Private Motel · Cambé & Londrina</span><a href="#a-experiencia" aria-label="Descubra a experiência Private">Descubra <span aria-hidden="true">↓</span></a><span>Luxury After Dark</span></div></section>
<section id="a-experiencia" className={`${styles.manifesto} wrap`}><div data-reveal><p className="eyebrow">A arte de estar a dois</p><h2>Há lugares.<br/>E há <em>momentos.</em></h2><p className={styles.manifestoCopy}>O Private é um convite a desacelerar. À intimidade de um encontro, ao conforto de uma suíte, ao prazer de ficar um pouco mais.</p><Link className="text-link" href="/sobre-nos">Conheça nossa essência <Arrow/></Link></div><figure data-reveal data-delay="0.12"><Photo {...homeMedia.manifesto} sizes="(max-width: 767px) 90vw, 35vw"/><figcaption>Privacidade em cada detalhe.</figcaption></figure></section>
<section className={`${styles.flagship} wrap`}><div className={styles.flagshipHeading} data-reveal><p className="eyebrow">Nossa assinatura</p><h2>Suíte <em>Private</em></h2></div><PhotoLink href="/suites#suite-private" media={homeMedia.flagship} className={styles.flagshipPhoto} sizes="90vw"/><div className={styles.flagshipBottom} data-reveal><p className={styles.flagshipLead}>Dois pisos.<br/>Infinitas razões para ficar.</p><div><p>Piscina aquecida com cascata, hidromassagem e sauna. Um universo particular para viver o seu encontro.</p><div className={styles.price}><span>Período</span><strong>{suites[0].pricing.periodo}</strong><span>Consulte duração e condições</span></div></div><Link className="text-link" href="/suites#suite-private">Explore a Private <Arrow/></Link></div></section>
<section className={`${styles.collection} wrap`}><div className={styles.collectionHeading} data-reveal><p className="eyebrow">Encontre o seu lugar</p><h2>A cada encontro,<br/>uma <em>nova escolha.</em></h2><Link className="text-link" href="/suites">Todas as suítes <Arrow/></Link></div>{suites.slice(1).map((suite,index)=><article className={styles.suiteStory} key={suite.id} data-reveal><PhotoLink href={'/suites#'+suite.id} media={{src:suite.images[0],alt:suite.title}} sizes="(max-width: 767px) 90vw, 50vw"/><div className={styles.suiteStoryCopy}><span className={styles.storyIndex}>0{index+2}</span><h3>{suite.title.replace('Suíte ','')}</h3><p>{suite.highlights.join(' · ')}</p><div className={styles.price}><span>Período</span><strong>{suite.pricing.periodo}</strong></div><Link href={'/suites#'+suite.id} className="text-link">Descubra a suíte <Arrow/></Link></div></article>)}</section>
<section className={styles.immersion}><Photo {...homeMedia.atmosphere} sizes="100vw"/><div className={styles.immersionCopy} data-reveal><p className="eyebrow">Só vocês. Nada mais.</p><h2>O luxo de<br/><em>desligar do mundo.</em></h2><p>Privacidade, conforto e tempo.<br/>O essencial para estar presente.</p><ReservationLink className="text-link">Viva esse momento</ReservationLink></div></section>
<section className={styles.dining}><div className={`${styles.diningInner} wrap`}><div className={styles.diningPhoto} data-reveal><Photo {...homeMedia.gastronomy} sizes="(max-width: 767px) 90vw, 45vw"/><span>À mesa. A dois.</span></div><div className={styles.diningCopy} data-reveal data-delay="0.1"><p className="eyebrow">Cortesias gastronômicas</p><h2>Sem pressa.<br/><em>Com sabor.</em></h2><p>Pequenas pausas que fazem parte da experiência. Conheça as condições de cada cortesia.</p><dl>{meals.map(meal=><div key={meal.title}><dt>{meal.title}</dt><dd>{meal.horario.replace('Servido das ','')}</dd></div>)}</dl><Link href="/cortesias" className="text-link">Descubra nossas cortesias <Arrow/></Link><a href={site.menuPdf} target="_blank" rel="noopener noreferrer" className={styles.menuLink}>Explore o cardápio ↗</a></div></div></section>
<section className={`${styles.experiences} wrap`}><div className={styles.experienceHeading} data-reveal><p className="eyebrow">Celebre o que é seu</p><h2>Alguns encontros<br/>merecem <em>mais.</em></h2></div><div className={styles.experienceStories}>{experiences.map((experience,index)=><article key={experience.title} data-reveal data-delay={index*.12}><Photo src={experience.image} alt={experience.title} sizes="(max-width: 767px) 90vw, 42vw"/><h3>{experience.title}</h3><p>{experience.description}</p><Link className="text-link" href="/experiencias">Prepare esse momento <Arrow/></Link></article>)}</div></section>
<section className={styles.structure}><div className="wrap"><div className={styles.structureHeading} data-reveal><p className="eyebrow">Conforto que acolhe</p><h2>O cuidado está<br/><em>nos detalhes.</em></h2><Link href="/estrutura" className="text-link">Conheça nossa estrutura <Arrow/></Link></div><Photo {...homeMedia.structure} sizes="90vw"/><div className={styles.structureFoot}><span>Seu refúgio em Cambé.</span><span>Atendimento 24 horas.</span></div></div></section>
<section className={`${styles.offers} wrap`}><div data-reveal><p className="eyebrow">Mais motivos para voltar</p><h2>Encontros com<br/><em>algo a mais.</em></h2><Link className="text-link" href="/promocoes">Todas as promoções <Arrow/></Link></div><div>{promotions.map(promotion=><Link key={promotion.title} className={styles.offer} href="/experiencias"><div><h3>{promotion.title}</h3><p>{promotion.description}</p></div><Arrow/></Link>)}<p className="note">Promoções não cumulativas. Consulte condições e disponibilidade.</p></div></section>
<section className={`${styles.location} wrap`} data-reveal><p className="eyebrow">Perto de você. Longe da rotina.</p><h2>Nos encontramos<br/><em>em Cambé.</em></h2><p>{site.address}</p><div className={styles.locationLinks}><a href={site.maps} target="_blank" rel="noopener noreferrer" className="text-link">Google Maps <Arrow/></a><a href={site.waze} target="_blank" rel="noopener noreferrer" className="text-link">Waze <Arrow/></a><Link href="/contato" className="text-link">Fale com a gente <Arrow/></Link></div></section>
<section className={styles.closing} data-reveal><p className="eyebrow">O seu momento começa aqui</p><h2>Permita-se<br/><em>ficar.</em></h2><ReservationLink/><Link className="text-link" href="/reservas">Planeje sua reserva <Arrow/></Link></section><PopupCookies/>
</div></HomeMotion></PageShell>}
